// ============================================================================
// Errly — Auto-Migration Runner
// Runs pending Drizzle migrations on server startup
// ============================================================================

import { existsSync, readdirSync } from 'node:fs';
import { resolve } from 'node:path';
import { migrate } from 'drizzle-orm/better-sqlite3/migrator';
import { db } from './index.js';
import { logger } from '../utils/logger.js';

/**
 * Run all pending database migrations from the drizzle/ directory.
 *
 * This function is called during server startup BEFORE accepting requests.
 * Drizzle's migrate() is synchronous for SQLite, so it blocks startup briefly.
 *
 * Migration files are generated by `drizzle-kit generate` (run as part of
 * `npm run build`). On first deploy, the build step generates the initial
 * migration from the Drizzle schema. On subsequent deploys with schema changes,
 * new migration files are generated and applied.
 */
export function runMigrations(): void {
  // The drizzle/ directory is at the project root, which is the working
  // directory when running with `node dist/server/index.js`
  const migrationsDir = resolve('drizzle');

  // Check if the drizzle/ directory exists
  if (!existsSync(migrationsDir)) {
    logger.warn(
      'No migration files found in drizzle/ — run `npm run db:generate` to create them. ' +
      'Tables may not exist yet.',
      { migrationsDir }
    );
    return;
  }

  // Check if the directory contains any migration files
  // Drizzle migration directories contain .sql files
  let hasMigrationFiles = false;
  try {
    const entries = readdirSync(migrationsDir);
    hasMigrationFiles = entries.some(
      (entry) => entry.endsWith('.sql') || existsSync(resolve(migrationsDir, entry, 'migration.sql'))
    );
  } catch (err) {
    logger.warn('Failed to read drizzle/ directory', {
      error: err instanceof Error ? err.message : String(err),
    });
    return;
  }

  if (!hasMigrationFiles) {
    logger.warn(
      'No migration files found in drizzle/ — run `npm run db:generate` to create them. ' +
      'Tables may not exist yet.',
      { migrationsDir }
    );
    return;
  }

  try {
    logger.info('Running database migrations...', { migrationsDir });
    migrate(db, { migrationsFolder: migrationsDir });
    logger.info('Database migrations completed successfully.');
  } catch (err) {
    logger.error('Database migration failed', {
      error: err instanceof Error ? err.message : String(err),
      stack: err instanceof Error ? err.stack : undefined,
    });
    throw err;
  }
}
